In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("WTO working file.xlsx")

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93308 entries, 0 to 93307
Data columns (total 29 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   HS_6                                   93307 non-null  float64
 1   HS_6_4                                 93307 non-null  float64
 2   HS_6_2                                 93307 non-null  float64
 3   country                                93307 non-null  object
 4   Trade regime                           93307 non-null  object
 5   Names                                  93307 non-null  object
 6   Ед.изм                                 93307 non-null  object
 7   Sum of количество                      93307 non-null  float64
 8   Sum of стоимость - 1000 $              93308 non-null  float64
 9   Unit value of imports in $             93307 non-null  float64
 10  MFN duty rate                          93307 non-null  object
 11  MFN tariff in %                        93307 non-null  float64
 12  Applied tariff rate                    93307 non-null  float64
 13  Collected tariffs                      93307 non-null  float64
 14  subject to duty change                 93307 non-null  object
 15  Import of goods with no change         93307 non-null  float64
 16  Sum Of Import of goods with no change  93307 non-null  float64
 17  Share of imp with no shock             93307 non-null  float64
 18  ImportDemandElasticity if blank = 1    93307 non-null  float64
 19  New duty 50 cut                        93307 non-null  float64
 20  dt/(1+t)                               93307 non-null  float64
 21  Trade creation                         93307 non-null  float64
 22  trade diversion 1                      93307 non-null  float64
 23  Sum Of trade diversion 1               93307 non-null  float64
 24  trade diversion 2                      93307 non-null  float64
 25  trade diversion all                    93308 non-null  float64
 26  total trade effect                     93308 non-null  float64
 27  welfare effect                         93308 non-null  float64
 28  Traiff revenue change                  93308 non-null  float64
dtypes: float64(23), object(6)
memory usage: 20.6+ MB

In [32]:
df.head(1)

,HS_6,HS_6_4,HS_6_2,country,Trade regime,Names,Ед.изм,Sum of количество,Sum of стоимость - 1000 $,Unit value of imports in $,...,New duty 50 cut,dt/(1+t),Trade creation,trade diversion 1,Sum Of trade diversion 1,trade diversion 2,trade diversion all,total trade effect,welfare effect,Traiff revenue change
0,60420.0,604.0,6.0,Австралия,MFN,"Листья, ветки и другие части растений без цвет...",т,0.145,0.355,2.448276,...,5.0,-0.045455,0.030348,0.00231,0.082799,0.0,0.00231,0.032658,0.002449,-0.016117

In [24]:
#values_to_keep = [
#    '300212', '300211', '300215, ,300213', '300214', '300510', '300590', '300610', '300620', '300630','300640',
#    '300650','300670', '300691', '340700', '382100', '382200', '391740','300620', '392690','392620', '401511', 
#    '401519', '420613', '611510', '621010', '630790','841920', '841990', '842191', '852852', '300620','854370',
#    '871300', '871310', '871390', '871420', '900130', '900140', '900150', '900311', '900319', '900390', '900410',
#    '901180', '901811', '901812', '901813', '901814', '901819', '901820', '901832', '901841', '901849', '901850',
#    '901890', '901910', '901920', '902000', '902110', '902129', '902131', '902139', '902140', '902150', '902190',
#    '902213', '902214', '902219', '902221', '902230', '902290',  '902511', '902519', '901812', '902750','902780',
#    '902790','940210','940290','981000',
#]

In [35]:
values_to_keep = [
    300212, 300211, 300215, 300213, 300214, 300510, 300590, 300610, 300620, 300630,300640,
    300650,300670, 300691, 340700, 382100, 382200, 391740,300620, 392690,392620, 401511, 
    401519, 420613, 611510, 621010, 630790,841920, 841990, 842191, 852852, 300620,854370,
    871300, 871310, 871390, 871420, 900130, 900140, 900150, 900311, 900319, 900390, 900410,
    901180, 901811, 901812, 901813, 901814, 901819, 901820, 901832, 901841, 901849, 901850,
    901890, 901910, 901920, 902000, 902110, 902129, 902131, 902139, 902140, 902150, 902190,
    902213, 902214, 902219, 902221, 902230, 902290, 902511, 902519, 901812, 902750,902780,
    902790,940210,940290,981000
]

In [38]:
# Отфильтруйте строки, оставив только те, которые содержат нужные значения в столбце HS 6
filtered_df = df[df['HS_6'].isin(values_to_keep)]

In [39]:
filtered_df.to_excel('filtered_data.xlsx', index=False)

In [40]:
filtered_df

,HS_6,HS_6_4,HS_6_2,country,Trade regime,Names,Ед.изм,Sum of количество,Sum of стоимость - 1000 $,Unit value of imports in $,...,New duty 50 cut,dt/(1+t),Trade creation,trade diversion 1,Sum Of trade diversion 1,trade diversion 2,trade diversion all,total trade effect,welfare effect,Traiff revenue change
26,382200.0,3822.0,38.0,Австралия,MFN,Реагенты диагностические или лабораторные на п...,т,0.000000,0.000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
30,392690.0,3926.0,39.0,Австралия,MFN,Изделия прочие из пластмасс и изделия из прочи...,т,0.008038,4.681,582.358796,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
53,630790.0,6307.0,63.0,Австралия,MFN,"Готовые изделия прочие, включая выкройки одежд...",т,0.000000,0.000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
131,854370.0,8543.0,85.0,Австралия,MFN,"Машины электрические и аппаратура, имеющие инд...",шт.,0.000000,0.000,0.000000,...,0.0,0.0,0.0,0.0,86.337674,0.0,0.0,0.0,0.0,0.0
144,902290.0,9022.0,90.0,Австралия,MFN,"Аппаратура, основанная на использовании рентге...",т,0.176500,46.045,260.878187,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93191,902780.0,9027.0,90.0,Япония,MFN,Приборы и аппаратура для физического или химич...,шт.,0.000000,0.000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
93193,902790.0,9027.0,90.0,Япония,MFN,Приборы и аппаратура для физического или химич...,шт.,0.000000,0.000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
93194,902790.0,9027.0,90.0,Япония,MFN,Приборы и аппаратура для физического или химич...,т,0.002270,8.840,3894.273128,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
93195,902790.0,9027.0,90.0,Япония,MFN,Приборы и аппаратура для физического или химич...,т,0.038010,42.219,1110.734017,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
93237,940290.0,9402.0,94.0,Япония,MFN,"Мебель медицинская, хирургическая, стоматологи...",т,65.498800,404.383,6.173899,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93308 entries, 0 to 93307
Data columns (total 29 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   HS 6                                   93307 non-null  float64
 1   Unnamed: 1                             93307 non-null  float64
 2   Unnamed: 2                             93307 non-null  float64
 3   country                                93307 non-null  object
 4   Trade regime                           93307 non-null  object
 5   Names                                  93307 non-null  object
 6   Ед.изм                                 93307 non-null  object
 7   Sum of количество                      93307 non-null  float64
 8   Sum of стоимость - 1000 $              93308 non-null  float64
 9   Unit value of imports in $             93307 non-null  float64
 10  MFN duty rate                          93307 non-null  object
 11  MFN tariff in %                        93307 non-null  float64
 12  Applied tariff rate                    93307 non-null  float64
 13  Collected tariffs                      93307 non-null  float64
 14  subject to duty change                 93307 non-null  object
 15  Import of goods with no change         93307 non-null  float64
 16  Sum Of Import of goods with no change  93307 non-null  float64
 17  Share of imp with no shock             93307 non-null  float64
 18  ImportDemandElasticity if blank = 1    93307 non-null  float64
 19  New duty 50 cut                        93307 non-null  float64
 20  dt/(1+t)                               93307 non-null  float64
 21  Trade creation                         93307 non-null  float64
 22  trade diversion 1                      93307 non-null  float64
 23  Sum Of trade diversion 1               93307 non-null  float64
 24  trade diversion 2                      93307 non-null  float64
 25  trade diversion all                    93308 non-null  float64
 26  total trade effect                     93308 non-null  float64
 27  welfare effect                         93308 non-null  float64
 28  Traiff revenue change                  93308 non-null  float64
dtypes: float64(23), object(6)
memory usage: 20.6+ MB